<%@ Page Title="" Language="C#" MasterPageFile="~/AdminHome.Master" AutoEventWireup="true" CodeBehind="AdminCreate.aspx.cs" Inherits="Project_v1.WebForm5" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br />
    <asp:SqlDataSource ID="BusDataSource" runat="server" ConnectionString="<%$ConnectionStrings:database %>"

        SelectCommand="SELECT * FROM BusMasterRoute" 
        UpdateCommand="UPDATE BusMasterRoute SET Operator=@Operator,Source=@Source,Dest=@Dest,Date=@Date,Cost=@Cost,RemainSeats=@RemainSeats WHERE BusNo=@BusNo"
        DeleteCommand="DELETE FROM BusMasterRoute WHERE BusNo=@BusNo"
        InsertCommand="INSERT INTO BusMasterRoute (Operator, Source,Dest,Date,Cost,RemainSeats) VALUES (@Operator, @Source,@Dest,@Date,@Cost,@RemainSeats)">

        <InsertParameters>
            <asp:ControlParameter Name="Operator" ControlID="TextBox1" Type="String" />
            <asp:ControlParameter Name="Source" ControlID="TextBox2" Type="String" />
            <asp:ControlParameter Name="Dest" ControlID="TextBox3" Type="String" />
            <asp:ControlParameter Name="Date" ControlID="TextBox4" Type="String" />
            <asp:ControlParameter Name="Cost" ControlID="TextBox5" Type="String" />
            <asp:ControlParameter Name="RemainSeats" ControlID="TextBox6" Type="String" />
        </InsertParameters>
        </asp:SqlDataSource>
    <asp:GridView DataKeyNames="BusNo" AllowSorting="true" AllowPaging="true" PageSize="3" DataSourceID="BusDataSource" ID="GridView1" runat="server" Height="145px" Width="184px" AutoGenerateColumns="false" CellPadding="5" CellSpacing="5" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
        <Columns>
            <asp:BoundField DataField="BusNo" HeaderText="Route No" />
            <asp:BoundField DataField="Operator" SortExpression="Operator" HeaderText="Operator" />
            <asp:BoundField DataField="Source" HeaderText="Source" />
            <asp:BoundField DataField="Dest" HeaderText="Destination" />
            <asp:BoundField DataField="Date" HeaderText="Date" />
            <asp:BoundField DataField="Cost" SortExpression="Cost" HeaderText="Ticket Price" />
            <asp:BoundField DataField="RemainSeats" HeaderText="RemainSeats" />
        </Columns>
    </asp:GridView>
    <br />
    
    <div class="insertfields" >
       
        <asp:TextBox  ID="TextBox1" Text="Operator" runat="server" onclick="this.value='';"/>
        <asp:TextBox ID="TextBox2" Text="Source" runat="server" onclick="this.value='';" />
        <asp:TextBox ID="TextBox3" Text="Dest" runat="server" onclick="this.value='';" />
        <asp:TextBox ID="TextBox4" TextMode="Date" Text="Date" runat="server" />
        <asp:TextBox ID="TextBox5"  Text="Cost" runat="server" onclick="this.value='';" />
        <asp:TextBox id="TextBox6"  Text="RemainSeats" runat="server" onclick="this.value='';" />

    </div>
    <br />
    <asp:Button ID="Button1" runat="server" Text="Insert" OnClick="Button1_Click" />
    

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
