<%@ Page Title="" Language="C#" MasterPageFile="~/Customer.Master" AutoEventWireup="true" CodeBehind="Bookings.aspx.cs" Inherits="Project_v1.WebForm8" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Label ID="Label1" runat="server" />
     <asp:SqlDataSource ID="BookingDataSource" runat="server" ConnectionString="<%$ConnectionStrings:database %>"
 
        SelectCommand="SELECT * FROM BookingsMain WHERE (CustId=@CustId)" 
        DeleteCommand="DELETE FROM BookingsMain WHERE Pnr=@Pnr">
          <SelectParameters>
            <asp:ControlParameter Name="CustId" ControlID="Label1" PropertyName="Text"  />
            
           
        </SelectParameters>
        
        </asp:SqlDataSource>
    <br />
     <asp:GridView DataKeyNames="Pnr" OnRowDeleting="Grid_del" AllowSorting="true" AllowPaging="true" PageSize="3" DataSourceID="BookingDataSource" ID="GridView1" runat="server" Height="145px" Width="184px" AutoGenerateColumns="false" CellPadding="5" CellSpacing="5" AutoGenerateDeleteButton="true">
        <Columns>
            <asp:BoundField DataField="Pnr" HeaderText="Pnr" />
            <asp:BoundField DataField="CustId" HeaderText="Customer Id" />
            <asp:BoundField DataField="BusNo" HeaderText="Route No" />
            <asp:BoundField DataField="Operator" SortExpression="Operator" HeaderText="Operator" />
            <asp:BoundField DataField="Source" HeaderText="Source" />
            <asp:BoundField DataField="Dest" HeaderText="Destination" />
            <asp:BoundField DataField="Date" SortExpression="Date" HeaderText="Date" />
            <asp:BoundField DataField="Cost" SortExpression="Cost" HeaderText="Ticket Price" />
        </Columns>
    </asp:GridView>
    <asp:Label ID="Label2" runat="server" />

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>
